# Site settings
title: Frequency Precision
description: Frequency Precision website...
url: "http://frequency-precision" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
