# Site settings
title: Clementine Oliver - Fabrics for Interiors
description: Fabrics for Interiors - Wool/Linen/Cashmere
url: "http://clementineoliver" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
